### ISSUE TITLE
Static host entry

### ISSUE THREAD

**Issue by eigenphase** [sle118/squeezelite-esp32#214]
Is it possible to add a static host entry locally to the device and if not implement such an function?
I would like for example to resolve example.intra.example.net to 10.227.67.2. I do not want to rely on "external" servers or services such as DNS.

**Background** When playing a file to my squeezelite, what actually seems to happen is that the squeezelite box sends a request **back** to the system which requested it (in my case, Home Assistant). Very bad protocol design, in my opinion but that's just the way how squeezebox protocol seems to work.
Problem: I cannot (easily) influence the URL that the requesting device requests to play. For example, my system is Home Assistant and when I request to play a file to my squeezelite-esp32 box, it tried to request the media file via http://example.intra.example.com. However, this name is not resolvable in the network my squeezebox is in. 
I have filed a [bug report at Home Assistant ](https://github.com/home-assistant/core/issues/82713) to make this URL configurable but there doesn't seem to be much traction.

Alternatively it would help if the squeezebox would just resolve this wrong name by itself.

If this is not possible yet, I would be hoping it can be implemented because a hosts file is part of any TCP/IP stack.

**Comment by sle118** [comment]
Since this is an embedded system, its capabilities are limited. I have not explored this possibility, but this is very much an edge case and there's literally just a few kB of flash space available on our current partition scheme so unfortunately this isn't something that I can consider implementing at this point.

I think your best option is to setup a small local DNS server, where you can configure the IP addresses you want, and then make sure your DHCP sends that DNS to its clients. As far as I know, some Wi-Fi access points/routers have limited but very capable features to help you there. Hoping this helps.
