### ISSUE TITLE
Bluetooth reconnect does not work

### ISSUE THREAD

**Issue by r1ckdu** [sle118/squeezelite-esp32#389]
### Describe the bug
After rebooting and sucessfully connecting + playing to a bluetooth sink I switch that sink off with its power button and turn it back on. It reconnects but the player does not play anymore.

### Preliminary Information

1. Current / 2.1670-16
2. Not sure if Plugin is important for this

### Hardware Details

Please describe your hardware setup:

- ESP32 WROVER
- Dev Board
- Bluetooth streaming
- Only Power

### NVS Settings

Follow these steps to share your NVS settings:

1. Open the web UI of your device.
2. Click on the "Credit" tab.
3. Enable the "Show NVS Editor" checkbox. This allows you to view or change the NVS configuration even when not in recovery mode.
4. Navigate to the "NVS Editor" tab.
5. Scroll to the bottom and click "Download Config".
6. Share the downloaded content here.

### Logs

I skipped the logs for now - maybe this is obvious from the description and I just missed in the docs? I can provide logs any time, hope this is not a mistake.

### Issue Description

1.Does not reconnect to play 
2. Should play again
3. Connect on boot - play - restart sink -> No Audio :)

**Comment by sle118** [comment]
Playing to a Bluetooth sink is not the primary goal of this project. It is an artefact of the original development efforts that we decided to leave there for convenience, but I have little time or interest to make that evolve beyond what it is already. 

So I'll go with the "it is by design" answer here. Maybe someone will have the motivation to improve upon the original implementation when I manage to push the refactored project later this spring, but for now The current branch is for stability improvements rather than feature implementation
